WHENEVER SQLERROR EXIT SQL.SQLCODE
SET PAGES 200 LINES 220 FEEDBACK OFF VERIFY OFF SERVEROUTPUT ON
DEF PDB='&1'
SELECT instance_name, host_name, status FROM v$instance;
SELECT name, open_mode FROM v$pdbs WHERE name = UPPER('&&PDB');
ALTER SESSION SET CONTAINER=&&PDB;
SELECT SYS_CONTEXT('USERENV','CON_NAME') AS con_name FROM dual;
SELECT name, open_mode FROM v$pdbs WHERE name = SYS_CONTEXT('USERENV','CON_NAME');
EXIT
