SET SERVEROUTPUT ON FEEDBACK OFF VERIFY OFF
DEF PDB='&1'
DEF HOLD_SECONDS='&2'
DEF WORKER_ID='&3'
ALTER SESSION SET CONTAINER=&&PDB;
BEGIN
  DBMS_APPLICATION_INFO.SET_MODULE('MONITOR_V2_DEMO_AAS_CPU', 'worker_&&WORKER_ID');
END;
/
DECLARE
  l_end_ts TIMESTAMP := SYSTIMESTAMP + NUMTODSINTERVAL(TO_NUMBER('&&HOLD_SECONDS'), 'SECOND');
  l_n NUMBER := 0;
  l_x NUMBER := 0;
BEGIN
  WHILE SYSTIMESTAMP < l_end_ts LOOP
    l_n := l_n + 1;
    l_x := l_x + SQRT(MOD(l_n, 1000000) + 1);
    IF MOD(l_n, 100000) = 0 THEN
      NULL;
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('AAS_CPU_WORKER_DONE worker=&&WORKER_ID loops=' || l_n || ' checksum=' || ROUND(l_x,2));
END;
/
EXIT
