WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON FEEDBACK ON VERIFY OFF
DEF PDB='&1'
DEF HOLD_SECONDS='&2'
ALTER SESSION SET CONTAINER=&&PDB;
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
BEGIN DBMS_APPLICATION_INFO.SET_MODULE('MONITOR_V2_DEMO_LOCK_HOLDER','FLEXING_LOCK_DEMO'); END;
/
DECLARE
  l_handle VARCHAR2(128);
  l_result NUMBER;
BEGIN
  DBMS_LOCK.ALLOCATE_UNIQUE('MONITOR_V2_DEMO_APPLICATION_LOCK', l_handle);
  l_result := DBMS_LOCK.REQUEST(l_handle, DBMS_LOCK.X_MODE, 0, FALSE);
  DBMS_OUTPUT.PUT_LINE('LOCK_HOLDER_RESULT=' || l_result);
  DBMS_OUTPUT.PUT_LINE('LOCK_HOLDER_SLEEP_SECONDS=&&HOLD_SECONDS');
  DBMS_LOCK.SLEEP(TO_NUMBER('&&HOLD_SECONDS'));
  l_result := DBMS_LOCK.RELEASE(l_handle);
  DBMS_OUTPUT.PUT_LINE('LOCK_HOLDER_RELEASE_RESULT=' || l_result);
END;
/
EXIT
