WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON FEEDBACK OFF VERIFY OFF
DEF PDB='&1'
DEF HOLD_SECONDS='&2'
DEF N='&3'
ALTER SESSION SET CONTAINER=&&PDB;
BEGIN DBMS_APPLICATION_INFO.SET_MODULE('MONITOR_V2_DEMO_SESSION','SESSION_&&N'); END;
/
BEGIN
  DBMS_LOCK.SLEEP(TO_NUMBER('&&HOLD_SECONDS'));
END;
/
EXIT
