WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON FEEDBACK ON VERIFY OFF
DEF PDB='&1'
DEF WAIT_SECONDS='&2'
ALTER SESSION SET CONTAINER=&&PDB;
BEGIN DBMS_APPLICATION_INFO.SET_MODULE('MONITOR_V2_DEMO_LOCK_WAITER','FLEXING_LOCK_DEMO'); END;
/
DECLARE
  l_handle VARCHAR2(128);
  l_result NUMBER;
BEGIN
  DBMS_LOCK.ALLOCATE_UNIQUE('MONITOR_V2_DEMO_APPLICATION_LOCK', l_handle);
  l_result := DBMS_LOCK.REQUEST(l_handle, DBMS_LOCK.X_MODE, TO_NUMBER('&&WAIT_SECONDS'), TRUE);
  DBMS_OUTPUT.PUT_LINE('LOCK_WAITER_RESULT=' || l_result);
END;
/
EXIT
